### ISSUE TITLE
Publish as package

### ISSUE THREAD

**Issue by gtrabanco** [theseyan/bkg#6]
Can this be available through bun install by publishing in npmjs?

Installation would be easier by using `bun add bkg`.

**Comment by paulocoghi** [comment]
Despite being made in Bun, I see bkg more of an external tool/cli than a javascript library.

Yes, it is possible to install packages from npmjs globally as well, to use them as a tool/cli, but inattentive developers could end up mistakenly installing bkg internally in their projects (which also is simple to solve, by letting it clear on the docs).

Anyway, the suggestion isn't bad, but I'm concerned that this could create more work to the maintainers _(I'm not one)_, because they would need to additionally publish the releases to npmjs and, on the other side, the project already provides a simple one command line to install it today.

Just my 2c.

**Comment by gtrabanco** [comment]
Yes, I see the point. You are right.

Have more sense have formulas for brew, apt... I will probably do brew formula its easy and I have done some for myself. I will let you know when I have it, not sure when.

In order to not make the repository of issues about similar stuff... I see the runtime creation use only latest version of bun. I do not know zig but probably a option to compile to latest canary bun would be nice and automate runtime creation on a repository and let developer choose unstable branch. Whats your opinion about? Whatever it is your opinion I see like an independent repository for runtimes could be (probably) a good idea.

**Comment by gtrabanco** [comment]
I clicked close accidentally 😅 Sorry

**Comment by paulocoghi** [comment]
Sure, no problem! About your last input, I like it a lot but it would be better if Sayan himself could answer as well, since I'm not a maintainer/contributor.

**Comment by theseyan** [comment]
I do plan to eventually publish bkg as an npm package (it won't be `bkg` however as the name is already taken).

To answer @gtrabanco, being able to choose Bun versions (including canary) is already on the roadmap & will definitely arrive in a newer version. There will also likely be a separate repository for Bun binaries as the next version of bkg will have an option to generate smaller binaries.

**Comment by gtrabanco** [comment]
Sorry I was going to make the homebrew package when I though about this issue... @theseyan you said you will rename bkg... Do you have any planned name? if you want that formulae to be on the brew core packages you should check if the name is taken in both sides before setting the final name. `bkg` is free on Homebrew. I think this could be accepted as core formulae.

**Comment by gtrabanco** [comment]
Forget it, it won't be accepted as core formulae. See this PR: https://github.com/Homebrew/homebrew-core/pull/105263

One requirements its to compile from source and resolve all dependencies which won't be done by the moment with brew.

So it's mandatory to support our own tap. Maybe we can request to be in bun tap repository when the formulae it's done: https://github.com/oven-sh/homebrew-bun
